language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - python3 backend/manage.py makemigrations manager
  - python3 backend/manage.py makemigrations ttrs
  - python3 backend/manage.py makemigrations
  - python3 backend/manage.py migrate
  - coverage run --source='.' --omit='*/migrations/*' backend/manage.py test ttrs
  - coverage report -m
